name = "CautiousEngine"
uuid = "a9375480-48c5-4a87-a666-34a603b88abe"
authors = ["John Jackson", "University of Colorado Boulder"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
